version: '3.8'
services:
  app:
    build: .
    container_name: simple-python-server
    command: uvicorn main:app --host 0.0.0.0 --port 80 --reload --reload-include *
    ports:
      - 8080:80
    volumes:
      - .:/app
    depends_on:
      - redis
  redis:
    image: redis:alpine
    ports: 
      - 6444:6444
    volumes:
      - ./redis_data:/data
